### ISSUE TITLE
我怎么才能设置多个网盘链接呀。只有一个好鸡肋啊

### ISSUE THREAD

**Issue by BadeSummer** [Benature/lazy-kit#1]
我怎么才能设置多个网盘链接呀，只有一个跳转好鸡肋

**Comment by Benature** [comment]
1. 复制黏贴多几个文件，每个html里面放不同的链接
2. 把html里面的自动跳转改为超链接文本，达到点击跳转的效果。这样可以打开html文件后再跳转想去的链接。如果懒的话可以用markdown写好超链接再导出为html文件。

**Comment by Benature** [comment]
增加了[多网址目录跳转](https://github.com/Benature/lazy-kit/tree/master/url_jump), `muti_jump.html`那个.
