### ISSUE TITLE
我在家里很安全

### ISSUE THREAD

**Issue by WeileiZeng** [Benature/lazy-kit#2]
觉得这个功能的社会影响力有待商榷。学校的初衷是安全。这个插件提供了操作上的捷径，却不定是保卫安全健康的捷径

**Comment by Benature** [comment]
谢谢提醒，已经去掉了对单选的选择，只保留了个人基本信息的自动填充，这样和普通浏览器的表单自动填写应该无异了。
初心只是看同学们填表惰性大，收表同学一直在催促；以及有同学学号填错，給统计的同学也造成了一些小麻烦，因此想提供一些便捷。
的确没有太多考虑扩散后的影响 *（虽然我也没指望有几个人用）* ，谢谢指正！

**Comment by WeileiZeng** [comment]
👍
